steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA"
      - "."

images: ["$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA"]

options:
  logging: CLOUD_LOGGING_ONLY
