version: "3.9"

services:
  db:
    image: postgres:17.0
    container_name: postgres
    environment:
      POSTGRES_DB: epicook
      POSTGRES_USER: epicook
      POSTGRES_PASSWORD: epicook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
