version: "3.9"

services:
  db:
    image: postgres:17.0
    container_name: toki_db
    environment:
      POSTGRES_DB: toki
      POSTGRES_USER: toki
      POSTGRES_PASSWORD: toki
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
